### PR TITLE
AccessToken and RefreshToken Handlers - do not create a default inner handler. 

### LINKED ISSUE #109: AccessTokenHandler doesn't work with aspnet HttpClientFactory - should not create default inner handler?
Hey, been exploring the new [HttpClientFactory stuff](https://blogs.msdn.microsoft.com/webdev/2018/02/28/asp-net-core-2-1-preview1-introducing-httpclient-factory/) but with this code... 

    var services = new ServiceCollection();
    services
        .AddHttpClient("client")
        .AddHttpMessageHandler(() => new AccessTokenHandler(
            "https://demo.identityserver.io/connect/token",
            "client",
            "secret",
            "scope"));
    var serviceProvider = services.BuildServiceProvider();
    var httpClientFactory = serviceProvider.GetService<IHttpClientFactory>();
    httpClientFactory.CreateClient("client");

...I get this exception:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The 'InnerHandler' property must be null. 'DelegatingHandler' instances provided to 'HttpMessageHandlerBuilder' must not be reused or cached.
Handler: 'IdentityModel.Client.AccessTokenHandler'
  Source=Microsoft.Extensions.Http
  StackTrace:
   at Microsoft.Extensions.Http.HttpMessageHandlerBuilder.CreateHandlerPipeline(HttpMessageHandler primaryHandler, IEnumerable`1 additionalHandlers)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandlerEntry(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)
   at ConsoleApp1.Program.Main(String[] args) in E:\dev\damianh\IdentityModel2\ConsoleApp1\Program.cs:line 27
```

The reason is because of this check: https://github.com/aspnet/HttpClientFactory/blob/dev/src/Microsoft.Extensions.Http/HttpMessageHandlerBuilder.cs#L78-L80 which, on the face of it, seems reasonable. It also appears that the expected usage of a _delegating_ http message handler is that the InnerHandler is to be set from the outside and is popsicle immutable on first `SendAsync`.
- https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/DelegatingHandler.cs#L53
- https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/DelegatingHandler.cs#L91-L101

Thus I think `AccessTokenHandler` should not create a default inner handler here https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/AccessTokenHandler.cs#L82 . Same would also apply to the `RefreshTokenHandler` here: https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/RefreshTokenHandler.cs#L108

As usual, happy to send a PR removing these if you agree.

### PR DESCRIPTION
**Pull request by damianh**
Instead rely on it being set from the outside. Delegating handler already ensures that a value is set on first usage (and [prevents it from being changed after](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/DelegatingHandler.cs#L31)).

Fixes #109

### CODE REVIEW

**Comment by leastprivilege** [comment]
Which would be a breaking change..

Maybe we should add an `AccessTokenDelegatingHandler` and a `RefreshTokenDelegatingHandler` for that...?

**Comment by damianh** [comment]
Could add the new types alright. Wondering if other two should be marked obsolete(false) or not?

**Comment by leastprivilege** [comment]
I am confused about the difference between `DelegatingHandler` and `HttpMessageHandler` - some APIs use the latter (aka `BackChannelHandler`) - the new factory stuff uses the former...

IOW - we need both types for the time being - or am I missing something?

**Comment by damianh** [comment]
I think its to do with object lifecyle - one can create a DelegatingHandler and then pass it to something else that will subsequently set the `InnerHandler`. Been looking at other implementations, such as `DiagnosticsHandler`, and the general pattern _seems_ to be default param-less ctor and a ctor that take a HttpMessageHandler inner. None of them create a default innerhandler. I think this lifecyle is being enforced by this HttpClientFactory shizzle.

Removing the creation of a default here is indeed a breaking change. At the moment though the handlers are not usable with aspnet/HttpClientFactory.

@darrelmiller , hope you don't mind me tagging you; I (we) would appreciate any insights or advice here :)

**Comment by darrelmiller** [comment]
DelegatingHandler is just a special case of HttpMessageHandler that expects to be in a pipeline and will pass the request along to the next in the chain, aka the InnerHandler.   My standard guidance is to use a DelegatingHandler unless for some reason you have to use a HttpMessageHandler.

Usually you would only use HttpMessageHandler for handlers that are at the end of a chain, like HttpClientHandler, or a MockingHandler.

**Comment by damianh** [comment]
Thanks @darrelmiller ! 

Any opinion on a DelegatingHandler implementation creating a _default_ InnerHandler vs expecting it to always be either passed in via ctor OR have InnerHandler be set?

**Comment by darrelmiller** [comment]
The "I don't like magic" side of me would generally avoid creating an HttpClientHandler automatically if an InnerHandler isn't provided.  If you are creating a message handler pipeline you probably should be aware of where the message is getting passed along to.  Either that or you hand it off to a factory an expect it do whatever is necessary.

**Comment by leastprivilege** [comment]
> DelegatingHandler is just a special case of HttpMessageHandler that expects to be in a pipeline and will pass the request along to the next in the chain, aka the InnerHandler.

Shouldn't it be the other way round? An HttpMessageHandler is a special case of a DelegatingHandler that does **not** expect to be in a pipeline? Hence the inheritance hierarchy?

(yes I know that's nitpicking ;))

The ASP.NET team chose to use HttpMessageHandler for their transport abstractions, e.g.:

https://github.com/aspnet/security/blob/dev/src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationOptions.cs#L74

Wouldn't a delegate handler be more appropriate based on @darrelmiller guidance? @tratcher

@damianh Based on that, I think we should introduce the new types we discussed and mark the old ones as obsolete...

**Comment by Tratcher** [comment]
@darrelmiller pretty much covered it. If you're building or requesting middleware, make it a DelegatingHandler. If you're building or requesting a pipeline/transport, make it a HttpMessageHandler.

A DelegatingHandler setting its own inner handler is pretty strange. That should be left for whoever's assembling the pipeline. However, it doesn't hurt anything as InnerHandler can still be reset up until the first request: 
https://github.com/dotnet/corefx/blob/997c881b22e5f4ad852fe141974f548004beef5e/src/System.Net.Http/src/System/Net/Http/DelegatingHandler.cs#L27-L34

I don't see any reason for you to add new types or changes to the existing types.

HttpClientFactory assembles middleware into a pipeline so it asks for DelegatingHandlers.

RemoteAuthOptions only needs a HttpMessageHandler because it's used to set/mock the whole pipeline. You're welcome to include middleware here, but you'll have to build the pipeline yourself.

**Comment by damianh** [comment]
Thanks for input all...

> However, it doesn't hurt anything as InnerHandler can still be reset up until the first request.

Wee issue with this is that the new HttpClientFactory checks if the InnerHandler has be set to prevent reusage even if it hasn't yet been used. However I dont know if exposing this  https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/DelegatingHandler.cs#L16 as a property would be sufficient without some race condition concerns.

Therefor @leastprivilage adding new types and marking current ones obsolete is prob way to go. If you agree, I'll update the PR.

**Comment by leastprivilege** [comment]
Yes please

> Wee issue with this is that the new HttpClientFactory checks if the InnerHandler has be set

@Tratcher could you add the relevant person to this conversation?

**Comment by Tratcher** [comment]
@rynowak

**Comment by rynowak** [comment]
> Wee issue with this is that the new HttpClientFactory checks if the InnerHandler has be set to prevent reusage even if it hasn't yet been used.

Yes, this is the case. The client factory will create and destroy pipelines of handlers as needed. The error checking is there to catch the usage mistake of trying to plug in a singleton handler. If this is blocking some kind of legitimate usage scenario I'd be interested to learn more.

**Comment by damianh** [comment]
Reverted the previous change and added the types as agreed.

File: src/IdentityModel/Client/AccessTokenDelegatingHandler.cs [hunk 1]
```diff
@@ -0,0 +1,191 @@
...
+        { }
+
+        /// <summary>
+        /// Initializes a new instance of the <see cref="AccessTokenDelegatingHandler"/> class.
+        /// </summary>
+        /// <param name="client">The client.</param>
+        /// <param name="scope">The scope.</param>
+        /// <param name="innerHandler">The inner handler.</param>
+        public AccessTokenDelegatingHandler(TokenClient client, string scope, HttpMessageHandler innerHandler = null)
+            : base(innerHandler)
```
Comment (damianh) [inline src/IdentityModel/Client/AccessTokenDelegatingHandler.cs:78]: Sending it to the base ctor instead.

**Comment by leastprivilege** [comment]
thanks!
